Add SBT builder Got: `java.lang.NoClassDefFoundError: javax/activation/DataSource` which is why I added `.jvmopts` file and some options in `aptgit.sbt`. Based on: - https://github.com/ohnosequences/sbt-s3-resolver/issues/58 - https://github.com/playframework/playframework/issues/7879#issuecomment-344438326